apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-yw5q
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-43256-0031-tenant/ci1t-43256-0031-app/devfile-sample-yw5q@sha256:e8c6350affcd908e8489eb5466fc0799b152b4c2d8298e28e5925767a45b7492
        name: my-nodejs
        resources: {}
status: {}
